@startuml 3GStore Containers
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
        
LAYOUT_WITH_LEGEND()

title 3GStore - Containers Diagram

Person(administrador, "Administrador", "Tem acesso a todas as telas, e usurá o software")

System_Boundary(3GStore, "Sistema de gerenciamento de estoque") {
    Container(PáginaAcesso, "Página Web Acesso", "React", "Página para mediar o acesso ao estoque")
    Container(AcessoEstoque, "API", "REACT/JavaScript e node, JWT", "Processa solicitações de acesso por meio da politica de acesso")
    Container(PáginaEstoque, "Página Web Adm", "React/JavaScript e node","Página para verificar o estoque em tempo real, entrada/saida e quantidade que ainda tem" )
    Container(PáginaEstoqueFornecedor, "Página Web Adm", "React/JavaScript e node","Página para verificar os fornecedores atuais" )
    Container(PáginaCadastrarProduto, "Página Web Adm","React/JavaScript e node", "Página de cadastramento de produtos.")
    Container(PáginaCadastrarFornecedores, "Página Web Adm","React/JavaScript e node", "Página de cadastramento de Fornecedores.")
    ContainerDb(BancoDados,"Banco de Dados do Estoque", "PostGreSQL", "Armazena dados dos fornecedores, produtos e Vendas")
    Container(DistribEstoque, "APIs","JavaScript e node", "Integração com APIs de vendas")
    Container(Integração, "API", "JavaScript e node", "Integração Api do Estoque e APIs externas de vendas.")
}
Rel(administrador, PáginaAcesso, "Uses", "HTTPS/JWT")
Rel_Neighbor(PáginaAcesso, AcessoEstoque, "deliver token-user", "uses", "HTTPS")
Rel(administrador, PáginaAcesso, "Uses", "HTTP/CDN")
Rel(administrador, PáginaEstoqueFornecedor, "Uses", "HTTPS/REST JWT")
Rel(administrador, PáginaCadastrarProduto, "Uses", "HTTPS/REST JWT")
Rel(administrador, PáginaCadastrarFornecedores, "Uses", "HTTPS/REST JWT")
Rel(PáginaEstoque, Integração, "Uses", "HTTP/CDN")
Rel(Integração, BancoDados, "write", "Uses","KeyAddress")
Rel_Back(BancoDados, DistribEstoque, "read", "Uses","KeyAddress")
@enduml
