@startuml VO Containers
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

title Sistema VO - Containers Diagram

Person(cliente, "Cliente", "Tipo de pessoa que consome vídeos no VO")
Person(administrador, "Administrador", "Tipo de pessoa que disponibiliza vídeos no VO")

System_Boundary(SistemaVO, "Sistema para publicação e consumo de vídeos em streaming") {
    Container(PáginaAcesso, "Página Web Acesso", "React", "Página para mediar o acesso ao VO")
    Container(PoliticaAcesso, "API", "Spring Boot, JWT, Java 17 or later e Dependências", "Processa solicitações de acesso por meio da politica de acesso")
    ContainerDb(BDUsuários, "Banco de Dados de Usuários", "PostGreSQL 17", "Armazena dados de usuários do Sistema VO")
    Container(PáginaVídeoAdm, "Página Web Adm", "React","Página para Inserção e Manutenção de Vídeos" )
    Container(ValidaçãoVídeo, "API","Spring Boot, Java 17 or later e Dependências", "Processa regras (youtube) de publicação e atualização de vídeos")
    ContainerDb(BDVídeos,"Banco de Dados de Vídeos", "Apache Cassandra 5.0", "Armazenamento e manutenção de vídeos com histórico de consumo de vídeos pelos usuários")
    Container(PáginaConsumoVídeo, "Página Web Vídeos","React", "Página de Consumo de Vídeo")
    Container(DistribVideos, "API", "Spring Boot, Java 17 or later e Dependências, CDNs", "Distribuição de Vídeos conforme demanda dos usuários")
}
Rel(administrador, PáginaAcesso, "Uses", "HTTPS/JWT")
Rel(cliente, PáginaAcesso, "Uses", "HTTPS/JWT")
Rel_Neighbor(PáginaAcesso, PáginaConsumoVídeo, "deliver token-user", "uses", "HTTPS")
Rel(administrador, PáginaVídeoAdm, "Uses", "HTTPS")
Rel_Neighbor(PáginaAcesso, PáginaVídeoAdm, "deliver token-user", "uses", "HTTPS")
Rel(cliente, PáginaConsumoVídeo, "Uses", "HTTP/CDN")
Rel(PáginaAcesso, PoliticaAcesso, "Uses", "HTTPS/REST JWT")
Rel(PoliticaAcesso, BDUsuários, "write/read", "Uses","IPAdress/Port") 
Rel(PáginaVídeoAdm, ValidaçãoVídeo, "Uses", "HTTP/REST")
Rel(ValidaçãoVídeo, BDVídeos, "read/write", "Uses","KeyAddress")
Rel(PáginaConsumoVídeo, DistribVideos, "Uses", "HTTP/CDN")
Rel(DistribVideos, BDVídeos, "write", "Uses","KeyAddress")
Rel_Back(DistribVideos, BDVídeos, "read", "Uses","KeyAddress")
@enduml